import { Platform, Category, Asset } from './types';

export const PLATFORMS: Platform[] = [
  { id: '1', name: 'Bisq', category: 'P2P', description: 'Decentralized P2P exchange network.', tags: ['No KYC', 'Recommended', 'Tor'], supportedAssets: ['BTC', 'XMR'], trustScore: 10, url: 'https://bisq.network' },
  { id: '2', name: 'Hodl Hodl', category: 'P2P', description: 'Global P2P Bitcoin trading platform.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC'], trustScore: 9, url: 'https://hodlhodl.com' },
  { id: '3', name: 'LocalMonero', category: 'P2P', description: 'P2P monero exchange.', tags: ['No KYC', 'Recommended'], supportedAssets: ['XMR'], trustScore: 10, url: 'https://localmonero.co' },
  { id: '4', name: 'AgoraDesk', category: 'P2P', description: 'P2P crypto exchange.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC'], trustScore: 10, url: 'https://agoradesk.com' },
  { id: '5', name: 'Peach Bitcoin', category: 'P2P', description: 'Mobile P2P exchange.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC'], trustScore: 9, url: 'https://peachbitcoin.com' },
  { id: '6', name: 'Robosats', category: 'P2P', description: 'Lightning network P2P exchange.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC'], trustScore: 10, url: 'https://learn.robosats.com' },
  { id: '7', name: 'Boltz', category: 'Exchange', description: 'Non-custodial account-free exchange.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 9, url: 'https://boltz.exchange' },
  { id: '8', name: 'FixedFloat', category: 'Exchange', description: 'Instant, fully automated exchange.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 8, url: 'https://fixedfloat.com' },
  { id: '9', name: 'SimpleSwap', category: 'Exchange', description: 'Crypto exchange platform.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 7, url: 'https://simpleswap.io' },
  { id: '10', name: 'SideShift', category: 'Exchange', description: 'No-account crypto shifts.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 7, url: 'https://sideshift.ai' },
  { id: '11', name: 'MorphToken', category: 'Exchange', description: 'Crypto exchange platform.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 7, url: 'https://morphtoken.com' },
  { id: '12', name: 'Flyp.me', category: 'Exchange', description: 'Accountless exchange platform.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 7, url: 'https://flyp.me' },
  { id: '13', name: 'Godex', category: 'Exchange', description: 'Crypto exchange platform.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 7, url: 'https://godex.io' },
  { id: '14', name: 'StealthEX', category: 'Exchange', description: 'Crypto exchange platform.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 7, url: 'https://stealthex.io' },
  { id: '15', name: 'ChangeNOW', category: 'Exchange', description: 'Crypto exchange platform.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 6, url: 'https://changenow.io' },
  { id: '16', name: 'Exolix', category: 'Exchange', description: 'Crypto exchange platform.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 7, url: 'https://exolix.com' },
  { id: '17', name: 'SwapSpace', category: 'Exchange', description: 'Crypto exchange aggregator.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 6, url: 'https://swapspace.co' },
  { id: '18', name: 'Letsexchange', category: 'Exchange', description: 'Crypto exchange platform.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 6, url: 'https://letsexchange.io' },
  { id: '19', name: 'Swapuz', category: 'Exchange', description: 'Crypto exchange platform.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 7, url: 'https://swapuz.com' },
  { id: '20', name: 'Xchange.me', category: 'Exchange', description: 'Crypto exchange aggregator.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 8, url: 'https://xchange.me' },
  { id: '21', name: 'CoinSwap', category: 'Exchange', description: 'Crypto exchange platform.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 8, url: 'https://coinswap.click' },
  { id: '22', name: 'AtomicDEX', category: 'Exchange', description: 'Decentralized exchange.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 9, url: 'https://atomicdex.io' },
  { id: '23', name: 'Komodo Wallet DEX', category: 'Wallet', description: 'Wallet with built-in DEX.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 9, url: 'https://komodoplatform.com' },
  { id: '24', name: 'Thorchain', category: 'Exchange', description: 'Decentralized liquidity network.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 8, url: 'https://thorchain.org' },
  { id: '25', name: 'Maya Protocol', category: 'Exchange', description: 'Decentralized liquidity network.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 8, url: 'https://maya-protocol.com' },
  { id: '26', name: 'Uniswap', category: 'Exchange', description: 'Decentralized exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://uniswap.org' },
  { id: '27', name: 'SushiSwap', category: 'Exchange', description: 'Decentralized exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://sushi.com' },
  { id: '28', name: 'PancakeSwap', category: 'Exchange', description: 'Decentralized exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://pancakeswap.finance' },
  { id: '29', name: '1inch', category: 'Exchange', description: 'Decentralized exchange aggregator.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://1inch.io' },
  { id: '30', name: 'Matcha', category: 'Exchange', description: 'Decentralized exchange aggregator.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://matcha.xyz' },
  { id: '31', name: 'Paraswap', category: 'Exchange', description: 'Decentralized exchange aggregator.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://paraswap.io' },
  { id: '32', name: 'Balancer', category: 'Exchange', description: 'Decentralized exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://balancer.fi' },
  { id: '33', name: 'Curve', category: 'Exchange', description: 'Decentralized exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://curve.fi' },
  { id: '34', name: 'dYdX', category: 'Exchange', description: 'Decentralized exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 6, url: 'https://dydx.trade' },
  { id: '35', name: 'GMX', category: 'Exchange', description: 'Decentralized exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 7, url: 'https://gmx.io' },
  { id: '36', name: 'Kwenta', category: 'Exchange', description: 'Decentralized exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 7, url: 'https://kwenta.io' },
  { id: '37', name: 'Apex Pro', category: 'Exchange', description: 'Decentralized exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 6, url: 'https://apex.exchange' },
  { id: '38', name: 'Vertex Protocol', category: 'Exchange', description: 'Decentralized exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 6, url: 'https://vertexprotocol.com' },
  { id: '39', name: 'ZigZag', category: 'Exchange', description: 'Decentralized exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 7, url: 'https://zigzag.exchange' },
  { id: '40', name: 'Loopring', category: 'Exchange', description: 'Decentralized exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 6, url: 'https://loopring.org' },
  { id: '41', name: 'DeversiFi', category: 'Exchange', description: 'Decentralized exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 6, url: 'https://deversifi.com' },
  { id: '42', name: 'OpenOcean', category: 'Exchange', description: 'Decentralized exchange aggregator.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://openocean.finance' },
  { id: '43', name: 'Rango Exchange', category: 'Exchange', description: 'Cross-chain exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 6, url: 'https://rango.exchange' },
  { id: '44', name: 'LiFi', category: 'Exchange', description: 'Cross-chain bridge/exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 6, url: 'https://li.fi' },
  { id: '45', name: 'THORSwap', category: 'Exchange', description: 'Decentralized exchange.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 8, url: 'https://thorswap.finance' },
  { id: '46', name: 'Biswap', category: 'Exchange', description: 'Decentralized exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://biswap.org' },
  { id: '47', name: 'Trader Joe', category: 'Exchange', description: 'Decentralized exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://traderjoexyz.com' },
  { id: '48', name: 'SpookySwap', category: 'Exchange', description: 'Decentralized exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://spookyswap.finance' },
  { id: '49', name: 'QuickSwap', category: 'Exchange', description: 'Decentralized exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://quickswap.exchange' },
  { id: '50', name: 'Raydium', category: 'Exchange', description: 'Decentralized exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://raydium.io' },
  { id: '51', name: 'TradeOgre', category: 'Exchange', description: 'No KYC crypto exchange.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 8, url: 'https://tradeogre.com' },
  { id: '52', name: 'NonKYC.io', category: 'Exchange', description: 'No KYC crypto exchange.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 9, url: 'https://nonkyc.io' },
  { id: '53', name: 'KYCNOT.ME', category: 'Exchange', description: 'Directory and info resource.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 9, url: 'https://kycnot.me' },
  { id: '54', name: 'OrangeFren', category: 'Exchange', description: 'Compare no-kyc instant exchanges.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 9, url: 'https://orangefren.com' },
  { id: '55', name: 'BitcoinVN Swap', category: 'Exchange', description: 'Crypto exchange.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 8, url: 'https://bitcoinvn.io' },
  { id: '56', name: 'Vexl', category: 'P2P', description: 'P2P platform.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 9, url: 'https://vexl.it' },
  { id: '57', name: 'Relai', category: 'Exchange', description: 'Bitcoin investment app.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 8, url: 'https://relai.app' },
  { id: '58', name: 'Pocket Bitcoin', category: 'Exchange', description: 'Bitcoin investment service.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 8, url: 'https://pocketbitcoin.com' },
  { id: '59', name: 'Azteco', category: 'Exchange', description: 'Bitcoin vouchers.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 8, url: 'https://azte.co' },
  { id: '60', name: 'BitValve', category: 'P2P', description: 'P2P platform.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 8, url: 'https://bitvalve.com' },
  { id: '61', name: 'LocalCoinSwap', category: 'P2P', description: 'P2P platform.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 8, url: 'https://localcoinswap.com' },
  { id: '62', name: 'Mycelium Local Trader', category: 'P2P', description: 'P2P platform.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 8, url: 'https://mycelium.com' },
  { id: '63', name: 'Paxful', category: 'P2P', description: 'Historical P2P platform.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 7, url: 'https://paxful.com' },
  { id: '64', name: 'Remitano', category: 'P2P', description: 'P2P platform.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 7, url: 'https://remitano.com' },
  { id: '65', name: 'CoinCola', category: 'P2P', description: 'P2P platform.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 7, url: 'https://coincola.com' },
  { id: '66', name: 'BuyCrypto.Today', category: 'Exchange', description: 'Crypto exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 7, url: 'https://buycrypto.today' },
  { id: '67', name: 'Bitpapa', category: 'P2P', description: 'P2P platform.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 8, url: 'https://bitpapa.com' },
  { id: '68', name: 'Coinffeine', category: 'P2P', description: 'P2P platform.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 9, url: 'https://coinffeine.com' },
  { id: '69', name: 'OpenBazaar', category: 'P2P', description: 'P2P marketplace.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 10, url: 'https://openbazaar.org' },
  { id: '70', name: 'Particl Marketplace', category: 'P2P', description: 'P2P marketplace.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 10, url: 'https://particl.io' },
  { id: '71', name: 'Haveno', category: 'P2P', description: 'P2P DEX.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 10, url: 'https://haveno.exchange' },
  { id: '72', name: 'Serai DEX', category: 'Exchange', description: 'Decentralized exchange.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 9, url: 'https://serai.exchange' },
  { id: '73', name: 'Samourai Whirlpool', category: 'Wallet', description: 'Coinjoin wallet.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 10, url: 'https://samouraiwallet.com/whirlpool' },
  { id: '74', name: 'JoinMarket', category: 'Wallet', description: 'Coinjoin wallet.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 10, url: 'https://github.com/JoinMarket-Org/joinmarket-clientserver' },
  { id: '75', name: 'Wasabi Wallet CoinJoin', category: 'Wallet', description: 'Coinjoin wallet.', tags: ['No KYC', 'Recommended'], supportedAssets: ['BTC', 'ETH'], trustScore: 9, url: 'https://wasabiwallet.io' },
  { id: '76', name: 'SideShift.ai', category: 'Exchange', description: 'Crypto exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 7, url: 'https://sideshift.ai' },
  { id: '77', name: 'SwapSwop', category: 'Exchange', description: 'Crypto exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 7, url: 'https://swapswop.io' },
  { id: '78', name: 'Coinswitch', category: 'Exchange', description: 'Crypto exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 6, url: 'https://coinswitch.co' },
  { id: '79', name: 'Guardarian', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://guardarian.com' },
  { id: '80', name: 'Paybis', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://paybis.com' },
  { id: '81', name: 'Switchere', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://switchere.com' },
  { id: '82', name: 'Bitexen', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://bitexen.com' },
  { id: '83', name: 'Bity', category: 'Exchange', description: 'Crypto exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 7, url: 'https://bity.com' },
  { id: '84', name: 'Mt Pelerin', category: 'Exchange', description: 'Crypto exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 7, url: 'https://mtpelerin.com' },
  { id: '85', name: 'PocketBits', category: 'Exchange', description: 'Crypto exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 6, url: 'https://pocketbits.in' },
  { id: '86', name: 'BitQuick', category: 'Exchange', description: 'Crypto exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 7, url: 'https://bitquick.com' },
  { id: '87', name: 'LiteBit', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://litebit.eu' },
  { id: '88', name: 'Coinmama', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 4, url: 'https://coinmama.com' },
  { id: '89', name: 'Changelly', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://changelly.com' },
  { id: '90', name: 'Transak', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 4, url: 'https://transak.com' },
  { id: '91', name: 'MoonPay', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 4, url: 'https://moonpay.com' },
  { id: '92', name: 'Ramp Network', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 4, url: 'https://ramp.network' },
  { id: '93', name: 'Banxa', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 4, url: 'https://banxa.com' },
  { id: '94', name: 'Simplex', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 4, url: 'https://simplex.com' },
  { id: '95', name: 'Mercuryo', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 4, url: 'https://mercuryo.io' },
  { id: '96', name: 'Wyre', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 4, url: 'https://sendwyre.com' },
  { id: '97', name: 'ShapeShift', category: 'Exchange', description: 'Crypto exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 6, url: 'https://shapeshift.com' },
  { id: '98', name: 'Edge Wallet Swap', category: 'Wallet', description: 'Crypto exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 6, url: 'https://edge.app' },
  { id: '99', name: 'Exodus Swap', category: 'Wallet', description: 'Crypto exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 6, url: 'https://exodus.com' },
  { id: '100', name: 'Cake Wallet Swap', category: 'Wallet', description: 'Crypto exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 7, url: 'https://cakewallet.com' },
  { id: '101', name: 'KuCoin', category: 'Exchange', description: 'Crypto exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 6, url: 'https://kucoin.com' },
  { id: '102', name: 'MEXC', category: 'Exchange', description: 'Crypto exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 6, url: 'https://mexc.com' },
  { id: '103', name: 'Gate.io', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://gate.io' },
  { id: '104', name: 'CoinEx', category: 'Exchange', description: 'Crypto exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 6, url: 'https://coinex.com' },
  { id: '105', name: 'Phemex', category: 'Exchange', description: 'Crypto exchange.', tags: ['Optional KYC'], supportedAssets: ['BTC', 'ETH'], trustScore: 6, url: 'https://phemex.com' },
  { id: '106', name: 'BingX', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://bingx.com' },
  { id: '107', name: 'Bitget', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://bitget.com' },
  { id: '108', name: 'Bybit', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://bybit.com' },
  { id: '109', name: 'XT.com', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://xt.com' },
  { id: '110', name: 'Hotbit', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 4, url: 'https://hotbit.io' },
  { id: '111', name: 'LATOKEN', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 4, url: 'https://latoken.com' },
  { id: '112', name: 'ProBit Global', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://probit.com' },
  { id: '114', name: 'CoinW', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://coinw.com' },
  { id: '115', name: 'BTSE', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://btse.com' },
  { id: '116', name: 'AscendEX', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://ascendex.com' },
  { id: '117', name: 'FMFW.io', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 3, url: 'https://fmfw.io' },
  { id: '118', name: 'LBank', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://lbank.com' },
  { id: '119', name: 'DigiFinex', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://digifinex.com' },
  { id: '120', name: 'BitMart', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://bitmart.com' },
  { id: '121', name: 'Coinsbit', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 4, url: 'https://coinsbit.io' },
  { id: '123', name: 'Toobit', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 5, url: 'https://toobit.com' },
  { id: '125', name: 'BVOX', category: 'Exchange', description: 'Crypto exchange.', tags: ['KYC Required'], supportedAssets: ['BTC', 'ETH'], trustScore: 4, url: 'https://bvox.com' },
  { id: '126', name: 'Betpanda', category: 'Casino', description: 'Crypto Casino.', tags: ['No KYC'], supportedAssets: ['BTC', 'ETH', 'LTC'], trustScore: 8, url: 'https://betpanda.io' },
  { id: '127', name: 'Coincasino', category: 'Casino', description: 'Crypto Casino.', tags: ['No KYC'], supportedAssets: ['BTC', 'ETH', 'LTC'], trustScore: 8, url: 'https://coincasino.com' },
  { id: '128', name: 'Cryptorino', category: 'Casino', description: 'Crypto Casino.', tags: ['No KYC'], supportedAssets: ['BTC', 'ETH', 'LTC'], trustScore: 8, url: 'https://cryptorino.com' },
  { id: '129', name: 'BC.Game', category: 'Casino', description: 'Crypto Casino.', tags: ['No KYC'], supportedAssets: ['BTC', 'ETH', 'LTC'], trustScore: 8, url: 'https://bc.game' },
];

export const TOOLS = []; // Removed as requested
